; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; Used ESP32 S3 module: ESP32-S3-WROOM-1-N4CT-ND

[env:lolin_s3]
platform = espressif32
board = lolin_s3
board_build.mcu = esp32s3
framework = arduino
monitor_speed = 921600
;upload_protocol = jlink
debug_tool = esp-builtin
; esp-builtin or jlink
debug_speed = 40000
upload_port = COM5

lib_deps = 
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    adafruit/Adafruit BusIO
	

; For this to work the file lolin_s3.json was modified.
; The modified version of the file is included in the folder "boards" of this project.
; You need to replace the original lolin_s3.json file in the %HOMEPATH%\.platformio\platforms\espressif32\boards directory
; Rename the file from this project to lolin_s3.json